# Generated by Django 5.0.2 on 2024-07-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Запись на консультацию', 'verbose_name_plural': 'Записи на консультации'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='FIO',
            field=models.TextField(blank=True, help_text='ФИО', null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.TextField(blank=True, help_text='Электронная почта', null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_marked_10',
            field=models.BooleanField(default=False, verbose_name='10:00-11:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_marked_11',
            field=models.BooleanField(default=False, verbose_name='11:00-12:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_marked_12',
            field=models.BooleanField(default=False, verbose_name='12:00-13:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_marked_13',
            field=models.BooleanField(default=False, verbose_name='13:00-14:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_marked_14',
            field=models.BooleanField(default=False, verbose_name='14:00-15:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_marked_16',
            field=models.BooleanField(default=False, verbose_name='16:00-17:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.TextField(blank=True, help_text='Телефон', null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Дата консультации', verbose_name='Дата консультации'),
        ),
    ]
