# Generated by Django 5.0.2 on 2024-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='FIO',
            field=models.CharField(blank=True, help_text='ФИО', max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
